"""Make e-mail unique and not nullable

Revision ID: 28609d8526ad
Revises: ba5cdfe8d72f
Create Date: 2021-07-17 13:59:35.319032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28609d8526ad'
down_revision = 'ba5cdfe8d72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(length=100),
               nullable=True)
    # ### end Alembic commands ###
