"""Remove unnecessary fields from `Post`

Revision ID: c9ac8a15fc9b
Revises: 28609d8526ad
Create Date: 2021-07-23 20:04:58.538420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ac8a15fc9b'
down_revision = '28609d8526ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('title', sa.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
